version: '3.1'

services:

  mongo:
    container_name: production-mongo
    image: mongo:6.0.13
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
      - "27017:27017"

  mongo-express:
    container_name: production-mongo-express
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
      ME_CONFIG_MONGODB_URL: mongodb://root:123@production-mongo:27017/

  rabbitmq:
    container_name: production-rabbitmq
    image: rabbitmq:3.12-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    container_name: production-api
    build: .
    image: production-api:latest
    restart: always
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      MONGO_HOST: production-mongo
      MONGO_PORT: 27017
      MONGO_USERNAME: root
      MONGO_PASSWORD: 123
      RABBITMQ_HOST: production-rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
