version: '3.1'

services:

  mongo:
    container_name: production-mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
      - "27017:27017"

  mongo-express:
    container_name: production-mongo-express
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
      ME_CONFIG_MONGODB_URL: mongodb://root:example@production-mongo:27017/

  api:
    container_name: production-api
    build: .
    image: production-api:latest
    restart: always
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      DATABASE_MONGO_HOST: production-mongo
      DATABASE_MONGO_PORT: 27017
      DATABASE_MONGO_USERNAME: root
      DATABASE_MONGO_PASSWORD: 123
