apiVersion: v1
kind: Service
metadata:
  name: production-rabbitmq-load-balancer-2
  labels:
    app: production-rabbitmq-load-balancer-2
spec:
  type: LoadBalancer
  selector:
    app: production-rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672