apiVersion: v1
kind: Service
metadata:
  name: production-rabbitmq-load-balancer
  labels:
    app: production-rabbitmq-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: production-rabbitmq
  ports:
    - protocol: TCP
      port: 80
      targetPort: 15672