apiVersion: v1
kind: Service
metadata:
  name: production-rabbitmq-service-temp
spec:
  type: NodePort
  selector:
    app: production-rabbitmq
  ports:
    - port: 80
      targetPort: 15672
      nodePort: 30002
