apiVersion: v1
kind: Service
metadata:
  name: production-mongo-service-temp
spec:
  type: NodePort
  selector:
    app: production-mongo
  ports:
    - port: 80
      targetPort: 27017
      nodePort: 30001
