apiVersion: v1
kind: Pod
metadata:
  name: production-mongo
  labels:
    app: production-mongo
spec:
  containers:
    - name: production-mongo
      image: mongo:6.0.13
      ports:
        - containerPort: 27017
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: production-mongo
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: production-mongo
              key: password
