apiVersion: v1
kind: Pod
metadata:
  name: production-mongo
  labels:
    app: production-mongo
spec:
  containers:
    - name: production-mongo
      image: mongo:6.0.13
      ports:
        - containerPort: 27017
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "123"
