apiVersion: v1
kind: Service
metadata:
  name: production-api-load-balancer
  labels:
    app: production-api-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: production-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080