apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-api-deployment
  labels:
    app: production-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: production-api
  template:
    metadata:
      labels:
        app: production-api
    spec:
      containers:
        - name: production-api
          image: gabrielgarciasp/production-api:latest
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_MONGO_HOST
              value: "production-mongo-service"
            - name: DATABASE_MONGO_PORT
              value: "27017"
            - name: DATABASE_MONGO_USERNAME
              value: "root"
            - name: DATABASE_MONGO_PASSWORD
              value: "123"
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 2
