apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-api-deployment
  labels:
    app: production-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: production-api
  template:
    metadata:
      labels:
        app: production-api
    spec:
      containers:
        - name: production-api
          image: gabrielgarciasp/production-api:latest
          ports:
            - containerPort: 80
          env:
            - name: MONGO_HOST
              value: "production-mongo-service"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: production-mongo
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: production-mongo
                  key: password
            - name: RABBITMQ_HOST
              value: "production-rabbitmq-service"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: production-rabbitmq
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: production-rabbitmq
                  key: password
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 2
