name: generate-version
on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Docker Hub
        run: docker login -u ${{env.DOCKER_USERNAME}} -p ${{env.DOCKER_PASSWORD}}

      - name: Build Docker image
        run: docker build -t ${{env.DOCKER_USERNAME}}/production-api:latest .

      - name: Push image to Docker Hub
        run: docker push ${{env.DOCKER_USERNAME}}/production-api:latest
