name: generate-version
on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Docker Hub
        run: docker login -u ${{env.DOCKER_USERNAME}} -p ${{env.DOCKER_PASSWORD}}

      - name: Build Docker image
        run: docker build -t ${{env.DOCKER_USERNAME}}/production-api:latest .

      - name: Push image to Docker Hub
        run: docker push ${{env.DOCKER_USERNAME}}/production-api:latest

  sonar-cloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Generate coverage report
        run: go test ./... -coverprofile=coverage.out

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=postech-fiap
            -Dsonar.projectKey=postech-fiap_production-api
            -Dsonar.sonar.host.url=https://sonarcloud.io
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
            -Dsonar.go.coverage.reportPaths=coverage.out
            -Dsonar.go.exclusions=**/cmd/**,**/repository/**,**/exception/**,**/http/**,**_test.go**
